---
language: python
python: "2.7"

  - pip install ansible

before_install:
  - sudo apt-get install -y pass
  - gem install bundler
  - openssl aes-256-cbc -K $encrypted_280b3fa2d7fd_key -iv $encrypted_280b3fa2d7fd_iv
    -in private-gpg.enc -out private-gpg -d
script:
  # deploy develop to the staging environment
  - cat private-gpg
  - sh scripts/setuppass
  - sh pass test
